### PR TITLE
fix issue #7 and #4

### LINKED ISSUE #4: Pressing brake and enabling drive switch should immediately change to drive mode
When in the `HV Enabled` mode, the driver must press on the brake pedal and flip on the drive switch in order to drive the car. The code must take noise in the brake pedal (in this case, the potentiometer) into account when checking whether the brake was pressed.

### LINKED ISSUE #7: Should throw fault when HV_enabled switch is flipped off during drive state
To exit fault state, both the hv enabled and drive switch must be disabled to enter LV state

### PR DESCRIPTION
**Pull request by MelodyLiu012**
fixes #7, now throws fault when HV_enabled switch is flipped off during drive state
fixes #4, pressing brake and enabling drive switch now immediately change to drive mode

### CODE REVIEW

File: main.c [hunk 1]
```diff
@@ -193,10 +195,15 @@ void main() {
...
-                            // Ask driver to reset drive switch and try again
-                            change_state(HV_ENABLED);
+                    // case BRAKE_NOT_PRESSED:
+                    //     if (!is_drive_requested()) {
+                    //         // Ask driver to reset drive switch and try again
+                    //         change_state(HV_ENABLED);
+                    //     }
+                    //     break;
+                    case HV_DISABLED_WHILE_DRIVE:
+                        if (is_hv_requested()) {
```
Comment (juliannguyen1) [inline main.c]: Only way to exit fault state is to enter LV state: refer to issue [here](https://github.com/FormulaRacingatUCDavis/VCU-Firmware-FE9/issues/7)

File: main.c [hunk 2]
```diff
@@ -155,18 +156,13 @@ void main() {
...
 
-                if (is_drive_requested()) {
-                    // Driver just flipped drive switch
-                    // Give driver some time to press brake
-                    __delay_ms(DRIVE_REQ_DELAY_MS);
-                    
-                    // Now check
-                    if (get_brake_pedal_value() >= PEDAL_MAX - BRAKE_ERROR_TOLERANCE) {
-                        // Brake pressed
+                if (get_brake_pedal_value() >= PEDAL_MAX - BRAKE_ERROR_TOLERANCE) {
```
Comment (juliannguyen1) [inline main.c]: In this code, the driver can turn on the drive switch and stay in HV enabled state, which is invalid.

Instead, the code should check if drive switch is enabled first before checking brakes. Driver must press brake while enabling drive or a fault state will occur.

**Review by juliannguyen1 — CHANGES_REQUESTED** [review]

**Review by juliannguyen1 — APPROVED** [review]
